# Generated by Django 3.2.4 on 2021-06-08 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
                ('jam_masuk', models.TimeField()),
                ('jam_keluar', models.TimeField()),
                ('status_checkin', models.BooleanField()),
            ],
            options={
                'db_table': 'absensi',
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_karyawan', models.CharField(max_length=255)),
                ('divisi', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'karyawan',
            },
        ),
    ]
